# Goto Repo Settings -> Actions -> Runner -> Click on Add Add Runner

# ******** Download The runner Package By running following command  *********

# Create a folder
    # $ mkdir actions-runner && cd actions-runner
# Download the latest runner package
    # $ curl -o actions-runner-linux-x64-2.320.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.320.0/actions-runner-linux-x64-2.320.0.tar.gz
# Optional: Validate the hash
    # $ echo "93ac1b7ce743ee85b5d386f5c1787385ef07b3d7c728ff66ce0d3813d5f46900  actions-runner-linux-x64-2.320.0.tar.gz" | shasum -a 256 -c
# Extract the installer
    # $ tar xzf ./actions-runner-linux-x64-2.320.0.tar.gz

# ******** Configure Runner **********

# Create the runner and start the configuration experience
     # $ ./config.sh --url https://github.com/CodeOps1891/AzureTask1 --token BKNSN6TVKP6ALA7BV3CGESTHIBZE4
# Last step, run it!
     # $ ./run.sh

# Now, in pipeline 
    #   runs-on: self-hosted

#   ********************************   PipeLine  *********************************



name: Run on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on Self-Hosted Runner
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
